export default () => {
	const { $i18n } = useNuxtApp()
	return {
		qualifications: [
			{ label: $i18n.translate("Primary school"), value: 0 },
			{ label: $i18n.translate("Prepatatory school"), value: 1 },
			{ label: $i18n.translate("High school"), value: 2 },
			{ label: $i18n.translate("Diploma"), value: 3 },
			{ label: $i18n.translate("Bachelor's degree"), value: 4 },
			{ label: $i18n.translate("Master's degree"), value: 5 },
			{ label: $i18n.translate("PHD degree"), value: 6 },
		],
		howKnewUs: [
			{ label: $i18n.translate("From a friend"), value: 0 },
			{ label: $i18n.translate("Twitter"), value: 1 },
			{ label: $i18n.translate("Youtube"), value: 2 },
		],
		countries: [
			{ label: $i18n.translate("Saudi Arabia"), value: 0 },
			{ label: $i18n.translate("Afghanistan"), value: 1 },
			{ label: $i18n.translate("Albania"), value: 2 },
			{ label: $i18n.translate("Algeria"), value: 3 },
			{ label: $i18n.translate("Andorra"), value: 4 },
			{ label: $i18n.translate("Angola"), value: 5 },
			{ label: $i18n.translate("Armenia"), value: 6 },
			{ label: $i18n.translate("Azerbaijan"), value: 7 },
			{ label: $i18n.translate("Bahamas"), value: 8 },
			{ label: $i18n.translate("Bahrain"), value: 9 },
			{ label: $i18n.translate("Bangladesh"), value: 10 },
			{ label: $i18n.translate("Belarus"), value: 11 },
			{ label: $i18n.translate("Bolivia"), value: 12 },
			{ label: $i18n.translate("Botswana"), value: 13 },
			{ label: $i18n.translate("Cameroon"), value: 14 },
			{ label: $i18n.translate("Congo"), value: 15 },
			{ label: $i18n.translate("Cuba"), value: 16 },
			{ label: $i18n.translate("Cyprus"), value: 17 },
			{ label: $i18n.translate("Egypt"), value: 18 },
			{ label: $i18n.translate("Gabon"), value: 19 },
			{ label: $i18n.translate("Gambia"), value: 20 },
			{ label: $i18n.translate("Georgia"), value: 21 },
			{ label: $i18n.translate("Ghana"), value: 22 },
			{ label: $i18n.translate("Greenland"), value: 23 },
			{ label: $i18n.translate("Guinea"), value: 24 },
			{ label: $i18n.translate("Honduras"), value: 25 },
			{ label: $i18n.translate("Iraq"), value: 26 },
			{ label: $i18n.translate("Jamaica"), value: 27 },
			{ label: $i18n.translate("Kuwait"), value: 28 },
			{ label: $i18n.translate("Lebanon"), value: 29 },
			{ label: $i18n.translate("Libya"), value: 30 },
			{ label: $i18n.translate("Morocco"), value: 31 },
			{ label: $i18n.translate("Mozambique"), value: 32 },
			{ label: $i18n.translate("Myanmar"), value: 33 },
			{ label: $i18n.translate("Namibia"), value: 34 },
			{ label: $i18n.translate("Nepal"), value: 35 },
			{ label: $i18n.translate("Nicaragua"), value: 36 },
			{ label: $i18n.translate("Oman"), value: 37 },
			{ label: $i18n.translate("Palestine"), value: 38 },
			{ label: $i18n.translate("Senegal"), value: 39 },
			{ label: $i18n.translate("Sudan"), value: 40 },
			{ label: $i18n.translate("Tunisia"), value: 41 },
			{ label: $i18n.translate("United Arab Emirates"), value: 42 },
		],

		nationalities: [
			{ label: $i18n.translate("Saudi Arabian"), value: "SA" },
			{ label: $i18n.translate("Afghan"), value: "AF" },
			{ label: $i18n.translate("Albanian"), value: "AL" },
			{ label: $i18n.translate("Algerian"), value: "DZ" },
			{ label: $i18n.translate("American"), value: "US" },
			{ label: $i18n.translate("American Samoan"), value: "AS" },
			{ label: $i18n.translate("Angolan"), value: "AO" },
			{ label: $i18n.translate("Anguillian"), value: "AI" },
			{ label: $i18n.translate("Antiguan"), value: "AG" },
			{ label: $i18n.translate("Argentine"), value: "AR" },
			{ label: $i18n.translate("Armenian"), value: "AM" },
			{ label: $i18n.translate("Aruban"), value: "AW" },
			{ label: $i18n.translate("Australian"), value: "AU" },
			{ label: $i18n.translate("Austrian"), value: "AT" },
			{ label: $i18n.translate("Azerbaijani"), value: "AZ" },
			{ label: $i18n.translate("Bahamian"), value: "BS" },
			{ label: $i18n.translate("Bahraini"), value: "BH" },
			{ label: $i18n.translate("Bangladeshi"), value: "BD" },
			{ label: $i18n.translate("Barbadian"), value: "BB" },
			{ label: $i18n.translate("Belarusian"), value: "BY" },
			{ label: $i18n.translate("Belgian"), value: "BE" },
			{ label: $i18n.translate("Belizean"), value: "BZ" },
			{ label: $i18n.translate("Beninese"), value: "BJ" },
			{ label: $i18n.translate("Bermudian"), value: "BM" },
			{ label: $i18n.translate("Bhutanese"), value: "BT" },
			{ label: $i18n.translate("Bolivian"), value: "BO" },
			{ label: $i18n.translate("Bosnian"), value: "BA" },
			{ label: $i18n.translate("Botswanan"), value: "BW" },
			{ label: $i18n.translate("Brazilian"), value: "BR" },
			{ label: $i18n.translate("British"), value: "GB" },
			{ label: $i18n.translate("British Virgin Islander"), value: "VG" },
			{ label: $i18n.translate("Bruneian"), value: "BN" },
			{ label: $i18n.translate("Bulgarian"), value: "BG" },
			{ label: $i18n.translate("Burkinabe"), value: "BF" },
			{ label: $i18n.translate("Burundian"), value: "BI" },
			{ label: $i18n.translate("Cambodian"), value: "KH" },
			{ label: $i18n.translate("Cameroonian"), value: "CM" },
			{ label: $i18n.translate("Canadian"), value: "CA" },
			{ label: $i18n.translate("Cape Verdean"), value: "CV" },
			{ label: $i18n.translate("Caymanian"), value: "KY" },
			{ label: $i18n.translate("Central African"), value: "CF" },
			{ label: $i18n.translate("Chadian"), value: "TD" },
			{ label: $i18n.translate("Chilean"), value: "CL" },
			{ label: $i18n.translate("Chinese"), value: "CN" },
			{ label: $i18n.translate("Christmas Islander"), value: "CX" },
			{ label: $i18n.translate("Colombian"), value: "CO" },
			{ label: $i18n.translate("Comorian"), value: "KM" },
			{ label: $i18n.translate("Congolese"), value: "CD" },
			{ label: $i18n.translate("Cook Islander"), value: "CK" },
			{ label: $i18n.translate("Costa Rican"), value: "CR" },
			{ label: $i18n.translate("Croatian"), value: "HR" },
			{ label: $i18n.translate("Cuban"), value: "CU" },
			{ label: $i18n.translate("Cypriot"), value: "CY" },
			{ label: $i18n.translate("Czech"), value: "CZ" },
			{ label: $i18n.translate("Danes"), value: "DK" },
			{ label: $i18n.translate("Djiboutian"), value: "DJ" },
			{ label: $i18n.translate("Dominican"), value: "DM" },
			{ label: $i18n.translate("Dominican"), value: "DO" },
			{ label: $i18n.translate("Dutch"), value: "NL" },
			{ label: $i18n.translate("Dutch Antillean"), value: "AN" },
			{ label: $i18n.translate("Ecuadorian"), value: "EC" },
			{ label: $i18n.translate("Egyptian"), value: "EG" },
			{ label: $i18n.translate("Emirati"), value: "AE" },
			{ label: $i18n.translate("Equatorial Guinean"), value: "GQ" },
			{ label: $i18n.translate("Eritrean"), value: "ER" },
			{ label: $i18n.translate("Estonian"), value: "EE" },
			{ label: $i18n.translate("Ethiopian"), value: "ET" },
			{ label: $i18n.translate("Falkland Islander"), value: "FK" },
			{ label: $i18n.translate("Faroese"), value: "FO" },
			{ label: $i18n.translate("Fijian"), value: "FJ" },
			{ label: $i18n.translate("Filipino"), value: "PH" },
			{ label: $i18n.translate("Finnish"), value: "FI" },
			{ label: $i18n.translate("French"), value: "FR" },
			{ label: $i18n.translate("French Guianese"), value: "GF" },
			{ label: $i18n.translate("French Polynesian"), value: "PF" },
			{ label: $i18n.translate("Futunan"), value: "WF" },
			{ label: $i18n.translate("Gabonese"), value: "GA" },
			{ label: $i18n.translate("Gambian"), value: "GM" },
			{ label: $i18n.translate("Georgian"), value: "GE" },
			{ label: $i18n.translate("German"), value: "DE" },
			{ label: $i18n.translate("Ghanaian"), value: "GH" },
			{ label: $i18n.translate("Gibraltarian"), value: "GI" },
			{ label: $i18n.translate("Greek"), value: "GR" },
			{ label: $i18n.translate("Grenadian"), value: "GD" },
			{ label: $i18n.translate("Guadeloupian"), value: "GP" },
			{ label: $i18n.translate("Guamanian"), value: "GU" },
			{ label: $i18n.translate("Guatemalan"), value: "GT" },
			{ label: $i18n.translate("Guinean"), value: "GN" },
			{ label: $i18n.translate("Guyanese"), value: "GY" },
			{ label: $i18n.translate("Haitian"), value: "HT" },
			{ label: $i18n.translate("Honduran"), value: "HN" },
			{ label: $i18n.translate("Hungarian"), value: "HU" },
			{ label: $i18n.translate("Icelander"), value: "IS" },
			{ label: $i18n.translate("Indian"), value: "IN" },
			{ label: $i18n.translate("Indonesian"), value: "ID" },
			{ label: $i18n.translate("Iranian"), value: "IR" },
			{ label: $i18n.translate("Iraqi"), value: "IQ" },
			{ label: $i18n.translate("Irish"), value: "IE" },
			{ label: $i18n.translate("Italian"), value: "IT" },
			{ label: $i18n.translate("Ivoirian"), value: "CI" },
			{ label: $i18n.translate("Jamaican"), value: "JM" },
			{ label: $i18n.translate("Japanese"), value: "JP" },
			{ label: $i18n.translate("Jordanian"), value: "JO" },
			{ label: $i18n.translate("Kazakhstani"), value: "KZ" },
			{ label: $i18n.translate("Kenyan"), value: "KE" },
			{ label: $i18n.translate("Kiribati"), value: "KI" },
			{ label: $i18n.translate("Kuwaiti"), value: "KW" },
			{ label: $i18n.translate("Kyrgyzstani"), value: "KG" },
			{ label: $i18n.translate("Latvian"), value: "LV" },
			{ label: $i18n.translate("Lebanese"), value: "LB" },
			{ label: $i18n.translate("Liberian"), value: "LR" },
			{ label: $i18n.translate("Libyan"), value: "LY" },
			{ label: $i18n.translate("Liechtensteiner"), value: "LI" },
			{ label: $i18n.translate("Lithuanian"), value: "LT" },
			{ label: $i18n.translate("Luxembourger"), value: "LU" },
			{ label: $i18n.translate("Macedonian"), value: "MK" },
			{ label: $i18n.translate("Malagasy"), value: "MG" },
			{ label: $i18n.translate("Malawian"), value: "MW" },
			{ label: $i18n.translate("Malaysian"), value: "MY" },
			{ label: $i18n.translate("Maldivian"), value: "MV" },
			{ label: $i18n.translate("Malian"), value: "ML" },
			{ label: $i18n.translate("Maltese"), value: "MT" },
			{ label: $i18n.translate("Marshallese"), value: "MH" },
			{ label: $i18n.translate("Martiniquai"), value: "MQ" },
			{ label: $i18n.translate("Mauritanian"), value: "MR" },
			{ label: $i18n.translate("Mauritian"), value: "MU" },
			{ label: $i18n.translate("Mexican"), value: "MX" },
			{ label: $i18n.translate("Miquelonnais"), value: "PM" },
			{ label: $i18n.translate("Moldovan"), value: "MD" },
			{ label: $i18n.translate("Monacan"), value: "MC" },
			{ label: $i18n.translate("Mongolian"), value: "MN" },
			{ label: $i18n.translate("Montenegrin"), value: "ME" },
			{ label: $i18n.translate("Montserratian"), value: "MS" },
			{ label: $i18n.translate("Moroccan"), value: "MA" },
			{ label: $i18n.translate("Mozambican"), value: "MZ" },
			{ label: $i18n.translate("Myanmarian"), value: "MM" },
			{ label: $i18n.translate("Nauruan"), value: "NR" },
			{ label: $i18n.translate("Nepalese"), value: "NP" },
			{ label: $i18n.translate("New Caledonian"), value: "NC" },
			{ label: $i18n.translate("New Zealander"), value: "NZ" },
			{ label: $i18n.translate("Ni-Vanuatu"), value: "VU" },
			{ label: $i18n.translate("Nicaraguan"), value: "NI" },
			{ label: $i18n.translate("Nigerian"), value: "NG" },
			{ label: $i18n.translate("Nigerien"), value: "NE" },
			{ label: $i18n.translate("Niuean"), value: "NU" },
			{ label: $i18n.translate("Norfolk Islander"), value: "NF" },
			{ label: $i18n.translate("North Korean"), value: "KP" },
			{ label: $i18n.translate("Northern Marianan"), value: "MP" },
			{ label: $i18n.translate("Norwegian"), value: "NO" },
			{ label: $i18n.translate("Omani"), value: "OM" },
			{ label: $i18n.translate("Pakistani"), value: "PK" },
			{ label: $i18n.translate("Palauan"), value: "PW" },
			{ label: $i18n.translate("Palestinian"), value: "PS" },
			{ label: $i18n.translate("Panamanian"), value: "PA" },
			{ label: $i18n.translate("Papuans"), value: "PG" },
			{ label: $i18n.translate("Paraguayan"), value: "PY" },
			{ label: $i18n.translate("Peruvian"), value: "PE" },
			{ label: $i18n.translate("Polish"), value: "PL" },
			{ label: $i18n.translate("Portuguese"), value: "PT" },
			{ label: $i18n.translate("Puerto Rican"), value: "PR" },
			{ label: $i18n.translate("Qatari"), value: "QA" },
			{ label: $i18n.translate("Romanian"), value: "RO" },
			{ label: $i18n.translate("Russian"), value: "RU" },
			{ label: $i18n.translate("Rwandan"), value: "RW" },
			{ label: $i18n.translate("Réunionese"), value: "RE" },
			{ label: $i18n.translate("Saint Helenian"), value: "SH" },
			{ label: $i18n.translate("Saint Lucian"), value: "LC" },
			{ label: $i18n.translate("Salvadoran"), value: "SV" },
			{ label: $i18n.translate("Samoan"), value: "WS" },
			{ label: $i18n.translate("Santomean"), value: "ST" },
			{ label: $i18n.translate("Senegalese"), value: "SN" },
			{ label: $i18n.translate("Serbian"), value: "RS" },
			{ label: $i18n.translate("Seychellois"), value: "SC" },
			{ label: $i18n.translate("Sierra Leonean"), value: "SL" },
			{ label: $i18n.translate("Singaporean"), value: "SG" },
			{ label: $i18n.translate("Slovak"), value: "SK" },
			{ label: $i18n.translate("Slovenian"), value: "SI" },
			{ label: $i18n.translate("Solomon Islander"), value: "SB" },
			{ label: $i18n.translate("Somali"), value: "SO" },
			{ label: $i18n.translate("South African"), value: "ZA" },
			{ label: $i18n.translate("South Korean"), value: "KR" },
			{ label: $i18n.translate("Spanish"), value: "ES" },
			{ label: $i18n.translate("Sri Lankan"), value: "LK" },
			{ label: $i18n.translate("Sudanese"), value: "SD" },
			{ label: $i18n.translate("Surinamer"), value: "SR" },
			{ label: $i18n.translate("Swazi"), value: "SZ" },
			{ label: $i18n.translate("Swede"), value: "SE" },
			{ label: $i18n.translate("Swiss"), value: "CH" },
			{ label: $i18n.translate("Syrian"), value: "SY" },
			{ label: $i18n.translate("Taiwanese"), value: "TW" },
			{ label: $i18n.translate("Tajikistani"), value: "TJ" },
			{ label: $i18n.translate("Tanzanian"), value: "TZ" },
			{ label: $i18n.translate("Thai"), value: "TH" },
			{ label: $i18n.translate("Tobagonian"), value: "TT" },
			{ label: $i18n.translate("Togolese"), value: "TG" },
			{ label: $i18n.translate("Tokelauan"), value: "TK" },
			{ label: $i18n.translate("Tongan"), value: "TO" },
			{ label: $i18n.translate("Tunisian"), value: "TN" },
			{ label: $i18n.translate("Turk"), value: "TR" },
			{ label: $i18n.translate("Turkmen"), value: "TM" },
			{ label: $i18n.translate("Turks and Caicos Islander"), value: "TC" },
			{ label: $i18n.translate("Tuvaluan"), value: "TV" },
			{ label: $i18n.translate("U.S. Minor Outlying Islander"), value: "UM" },
			{ label: $i18n.translate("Ugandan"), value: "UG" },
			{ label: $i18n.translate("Ukrainian"), value: "UA" },
			{ label: $i18n.translate("Uruguayan"), value: "UY" },
			{ label: $i18n.translate("Uzbek"), value: "UZ" },
			{ label: $i18n.translate("Vatican"), value: "VA" },
			{ label: $i18n.translate("Venezuelan"), value: "VE" },
			{ label: $i18n.translate("Vietnamese"), value: "VN" },
			{ label: $i18n.translate("Virgin Islander"), value: "VI" },
			{ label: $i18n.translate("Yemeni"), value: "YE" },
			{ label: $i18n.translate("Zambian"), value: "ZM" },
			{ label: $i18n.translate("Zimbabwean"), value: "ZW" },
		],

		cities: [
			{ label: $i18n.translate("Jubail"), value: 0 },
			{ label: $i18n.translate("Buraidah"), value: 1 },
			{ label: $i18n.translate("Riyadh"), value: 2 },
			{ label: $i18n.translate("Mecca"), value: 3 },
			{ label: $i18n.translate("Medina"), value: 4 },
			{ label: $i18n.translate("Tabuk"), value: 5 },
			{ label: $i18n.translate("Dammam"), value: 6 },
			{ label: $i18n.translate("Al Taeif"), value: 7 },
			{ label: $i18n.translate("Al Ahsaa"), value: 8 },
			{ label: $i18n.translate("Al Qatif"), value: 9 },
			{ label: $i18n.translate("Najran"), value: 10 },
			{ label: $i18n.translate("Hafr Albatin"), value: 11 },
			{ label: $i18n.translate("Dabaa"), value: 12 },
			{ label: $i18n.translate("Al Kharaj"), value: 13 },
			{ label: $i18n.translate("Yanbu`"), value: 14 },
			{ label: $i18n.translate("Khobar"), value: 15 },
			{ label: $i18n.translate("A'ror"), value: 16 },
			{ label: $i18n.translate("Sakaka"), value: 17 },
			{ label: $i18n.translate("Jizan"), value: 18 },
			{ label: $i18n.translate("Al Qarrayat"), value: 19 },
			{ label: $i18n.translate("Al Zahran"), value: 20 },
			{ label: $i18n.translate("Al Zelafa"), value: 21 },
			{ label: $i18n.translate("Al Bahah"), value: 22 },
			{ label: $i18n.translate("Al Rass"), value: 23 },
			{ label: $i18n.translate("Besha"), value: 24 },
			{ label: $i18n.translate("Sehat"), value: 25 },
			{ label: $i18n.translate("Sharora"), value: 26 },
			{ label: $i18n.translate("Bahra"), value: 27 },
			{ label: $i18n.translate("Afif"), value: 28 },
			{ label: $i18n.translate("Sabia"), value: 29 },
			{ label: $i18n.translate("Bariq"), value: 30 },
			{ label: $i18n.translate("Al Aflaj"), value: 31 },
			{ label: $i18n.translate("Al Bakiria"), value: 32 },
			{ label: $i18n.translate("Al Moznab"), value: 33 },
			{ label: $i18n.translate("Al Bada'e"), value: 34 },
			{ label: $i18n.translate("Riyadh Al Khabraa"), value: 35 },
			{ label: $i18n.translate("Abha"), value: 36 },
			{ label: $i18n.translate("Khamees Masheet"), value: 37 },
			{ label: $i18n.translate("Mahayel Aseer"), value: 38 },
			{ label: $i18n.translate("Al A'laya"), value: 39 },
			{ label: $i18n.translate("Aneeza"), value: 40 },
			{ label: $i18n.translate("Al Namaas"), value: 41 },
			{ label: $i18n.translate("Jeddah"), value: 42 },
		],

		branches: [
			{ label: $i18n.translate("Mecca"), value: 1 },
			{ label: $i18n.translate("Medina"), value: 2 },
			{ label: $i18n.translate("Al Ahsaa"), value: 3 },
			{ label: $i18n.translate("Jubail"), value: 4 },
			{ label: $i18n.translate("Dammam"), value: 5 },
			{ label: $i18n.translate("Hael"), value: 6 },
			{ label: $i18n.translate("Hafr Al-Baten"), value: 7 },
			{ label: $i18n.translate("Riyadh"), value: 8 },
			{ label: $i18n.translate("Al-Qusaim"), value: 9 },
			{ label: $i18n.translate("Al Bahah"), value: 10 },
			{ label: $i18n.translate("Al Jawf"), value: 11 },
			{ label: $i18n.translate("Northern borders"), value: 12 },
			{ label: $i18n.translate("Aseer"), value: 13 },
			{ label: $i18n.translate("Jazan"), value: 14 },
			{ label: $i18n.translate("Najran"), value: 15 },
			{ label: $i18n.translate("Tabuk"), value: 16 },
			{ label: $i18n.translate("Al Taeif"), value: 17 },
		],

		mobileCodes: [
			{ label: "+966", value: "966" },
			{ label: "+93", value: "93" },
			{ label: "+358", value: "358" },
			{ label: "+355", value: "355" },
			{ label: "+213", value: "213" },
			{ label: "+1684", value: "1684" },
			{ label: "+376", value: "376" },
			{ label: "+244", value: "244" },
			{ label: "+1264", value: "1264" },
			{ label: "+1268", value: "1268" },
			{ label: "+54", value: "54" },
			{ label: "+374", value: "374" },
			{ label: "+297", value: "297" },
			{ label: "+43", value: "43" },
			{ label: "+994", value: "994" },
			{ label: "+1242", value: "1242" },
			{ label: "+973", value: "973" },
			{ label: "+880", value: "880" },
			{ label: "+1246", value: "1246" },
			{ label: "+375", value: "375" },
			{ label: "+32", value: "32" },
			{ label: "+501", value: "501" },
			{ label: "+229", value: "229" },
			{ label: "+1441", value: "1441" },
			{ label: "+975", value: "975" },
			{ label: "+591", value: "591" },
			{ label: "+387", value: "387" },
			{ label: "+267", value: "267" },
			{ label: "+55", value: "55" },
			{ label: "+246", value: "246" },
			{ label: "+673", value: "673" },
			{ label: "+359", value: "359" },
			{ label: "+226", value: "226" },
			{ label: "+257", value: "257" },
			{ label: "+855", value: "855" },
			{ label: "+237", value: "237" },
			{ label: "+1", value: "1" },
			{ label: "+238", value: "238" },
			{ label: "+ 345", value: " 345" },
			{ label: "+236", value: "236" },
			{ label: "+235", value: "235" },
			{ label: "+56", value: "56" },
			{ label: "+86", value: "86" },
			{ label: "+61", value: "61" },
			{ label: "+57", value: "57" },
			{ label: "+269", value: "269" },
			{ label: "+242", value: "242" },
			{ label: "+243", value: "243" },
			{ label: "+682", value: "682" },
			{ label: "+506", value: "506" },
			{ label: "+225", value: "225" },
			{ label: "+385", value: "385" },
			{ label: "+53", value: "53" },
			{ label: "+357", value: "357" },
			{ label: "+420", value: "420" },
			{ label: "+45", value: "45" },
			{ label: "+253", value: "253" },
			{ label: "+1767", value: "1767" },
			{ label: "+1849", value: "1849" },
			{ label: "+593", value: "593" },
			{ label: "+20", value: "20" },
			{ label: "+503", value: "503" },
			{ label: "+240", value: "240" },
			{ label: "+291", value: "291" },
			{ label: "+372", value: "372" },
			{ label: "+251", value: "251" },
			{ label: "+500", value: "500" },
			{ label: "+298", value: "298" },
			{ label: "+679", value: "679" },
			{ label: "+33", value: "33" },
			{ label: "+594", value: "594" },
			{ label: "+689", value: "689" },
			{ label: "+241", value: "241" },
			{ label: "+220", value: "220" },
			{ label: "+995", value: "995" },
			{ label: "+49", value: "49" },
			{ label: "+233", value: "233" },
			{ label: "+350", value: "350" },
			{ label: "+30", value: "30" },
			{ label: "+299", value: "299" },
			{ label: "+1473", value: "1473" },
			{ label: "+590", value: "590" },
			{ label: "+1671", value: "1671" },
			{ label: "+502", value: "502" },
			{ label: "+224", value: "224" },
			{ label: "+245", value: "245" },
			{ label: "+509", value: "509" },
			{ label: "+379", value: "379" },
			{ label: "+504", value: "504" },
			{ label: "+852", value: "852" },
			{ label: "+36", value: "36" },
			{ label: "+354", value: "354" },
			{ label: "+91", value: "91" },
			{ label: "+62", value: "62" },
			{ label: "+98", value: "98" },
			{ label: "+964", value: "964" },
			{ label: "+353", value: "353" },
			{ label: "+972", value: "972" },
			{ label: "+39", value: "39" },
			{ label: "+1876", value: "1876" },
			{ label: "+81", value: "81" },
			{ label: "+962", value: "962" },
			{ label: "+77", value: "77" },
			{ label: "+254", value: "254" },
			{ label: "+686", value: "686" },
			{ label: "+850", value: "850" },
			{ label: "+82", value: "82" },
			{ label: "+965", value: "965" },
			{ label: "+996", value: "996" },
			{ label: "+856", value: "856" },
			{ label: "+371", value: "371" },
			{ label: "+961", value: "961" },
			{ label: "+266", value: "266" },
			{ label: "+231", value: "231" },
			{ label: "+218", value: "218" },
			{ label: "+423", value: "423" },
			{ label: "+370", value: "370" },
			{ label: "+352", value: "352" },
			{ label: "+853", value: "853" },
			{ label: "+389", value: "389" },
			{ label: "+261", value: "261" },
			{ label: "+265", value: "265" },
			{ label: "+60", value: "60" },
			{ label: "+960", value: "960" },
			{ label: "+223", value: "223" },
			{ label: "+356", value: "356" },
			{ label: "+692", value: "692" },
			{ label: "+596", value: "596" },
			{ label: "+222", value: "222" },
			{ label: "+230", value: "230" },
			{ label: "+52", value: "52" },
			{ label: "+691", value: "691" },
			{ label: "+373", value: "373" },
			{ label: "+377", value: "377" },
			{ label: "+976", value: "976" },
			{ label: "+382", value: "382" },
			{ label: "+1664", value: "1664" },
			{ label: "+212", value: "212" },
			{ label: "+258", value: "258" },
			{ label: "+95", value: "95" },
			{ label: "+264", value: "264" },
			{ label: "+674", value: "674" },
			{ label: "+977", value: "977" },
			{ label: "+31", value: "31" },
			{ label: "+599", value: "599" },
			{ label: "+687", value: "687" },
			{ label: "+64", value: "64" },
			{ label: "+505", value: "505" },
			{ label: "+227", value: "227" },
			{ label: "+234", value: "234" },
			{ label: "+683", value: "683" },
			{ label: "+672", value: "672" },
			{ label: "+1670", value: "1670" },
			{ label: "+968", value: "968" },
			{ label: "+92", value: "92" },
			{ label: "+680", value: "680" },
			{ label: "+970", value: "970" },
			{ label: "+507", value: "507" },
			{ label: "+675", value: "675" },
			{ label: "+595", value: "595" },
			{ label: "+51", value: "51" },
			{ label: "+63", value: "63" },
			{ label: "+872", value: "872" },
			{ label: "+48", value: "48" },
			{ label: "+351", value: "351" },
			{ label: "+1939", value: "1939" },
			{ label: "+974", value: "974" },
			{ label: "+40", value: "40" },
			{ label: "+7", value: "7" },
			{ label: "+250", value: "250" },
			{ label: "+262", value: "262" },
			{ label: "+290", value: "290" },
			{ label: "+1869", value: "1869" },
			{ label: "+1758", value: "1758" },
			{ label: "+508", value: "508" },
			{ label: "+1784", value: "1784" },
			{ label: "+685", value: "685" },
			{ label: "+378", value: "378" },
			{ label: "+239", value: "239" },
			{ label: "+221", value: "221" },
			{ label: "+381", value: "381" },
			{ label: "+248", value: "248" },
			{ label: "+232", value: "232" },
			{ label: "+65", value: "65" },
			{ label: "+421", value: "421" },
			{ label: "+386", value: "386" },
			{ label: "+677", value: "677" },
			{ label: "+252", value: "252" },
			{ label: "+27", value: "27" },
			{ label: "+211", value: "211" },
			{ label: "+34", value: "34" },
			{ label: "+94", value: "94" },
			{ label: "+249", value: "249" },
			{ label: "+597", value: "597" },
			{ label: "+47", value: "47" },
			{ label: "+268", value: "268" },
			{ label: "+46", value: "46" },
			{ label: "+41", value: "41" },
			{ label: "+963", value: "963" },
			{ label: "+886", value: "886" },
			{ label: "+992", value: "992" },
			{ label: "+255", value: "255" },
			{ label: "+66", value: "66" },
			{ label: "+670", value: "670" },
			{ label: "+228", value: "228" },
			{ label: "+690", value: "690" },
			{ label: "+676", value: "676" },
			{ label: "+1868", value: "1868" },
			{ label: "+216", value: "216" },
			{ label: "+90", value: "90" },
			{ label: "+993", value: "993" },
			{ label: "+1649", value: "1649" },
			{ label: "+688", value: "688" },
			{ label: "+256", value: "256" },
			{ label: "+380", value: "380" },
			{ label: "+971", value: "971" },
			{ label: "+44", value: "44" },
			{ label: "+598", value: "598" },
			{ label: "+998", value: "998" },
			{ label: "+678", value: "678" },
			{ label: "+58", value: "58" },
			{ label: "+84", value: "84" },
			{ label: "+1284", value: "1284" },
			{ label: "+1340", value: "1340" },
			{ label: "+681", value: "681" },
			{ label: "+967", value: "967" },
			{ label: "+260", value: "260" },
			{ label: "+263", value: "263" },
		],
		genders: [
			{ label: $i18n.translate("Male"), value: 0 },
			{ label: $i18n.translate("Female"), value: 1 },
		],

		coursePrices: [
			{ label: $i18n.translate("Free"), value: 0 },
			{ label: $i18n.translate("All paid"), value: 1 },
			{ label: $i18n.translate("Paid certificate"), value: 2 },
		],

		ticketStatus: [
			{ label: $i18n.translate("Solved"), value: 0 },
			{ label: $i18n.translate("Open"), value: 1 },
		],

		membershipTypes: [
			{ label: $i18n.translate("fulltime_member"), value: 1, price: 250 },
			{ label: $i18n.translate("parttime_member"), value: 2, price: 200 },
			{ label: $i18n.translate("affiliate_member"), value: 3, price: 150 },
		],

		levels: [
			{ label: $i18n.translate("Fair"), value: 0 },
			{ label: $i18n.translate("Good"), value: 1 },
			{ label: $i18n.translate("Very good"), value: 2 },
			{ label: $i18n.translate("Excellent"), value: 3 },
		],
	}
}
